---
- hosts: all
  become: yes
  tasks:
    - name: Installeer Nginx
      apt:
        name: nginx
        state: present

    - name: Configureer Nginx als load balancer
      # Voeg hier je configuratiestappen toe
      # Dit zal afhangen van je specifieke setup en vereisten

    - name: Zorg dat Nginx draait
      service:
        name: nginx
        state: started
        enabled: true

